name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_SERVER_IP }}
          username: ${{ secrets.HETZNER_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~  # Go to the home directory
            if [ ! -d "webhook-telegram" ]; then
              git clone https://github.com/meernahro/webhook-telegram.git
            fi
            cd webhook-telegram  # Ensure you're in the project directory
            git pull origin main  # Pull the latest changes
            docker stop flask-app || true  # Stop any running container
            docker rm flask-app || true    # Remove the old container
            docker rmi flask-app || true   # Remove the old image
            if [ -f Dockerfile ]; then
              docker build -t flask-app .    # Build the new image
            else
              echo "Dockerfile not found, exiting."
              exit 1
            fi
            docker run -d -p 80:5000 --name flask-app -e TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} -e TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }} flask-app:latest
