name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_SERVER_IP }}
          username: ${{ secrets.HETZNER_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~  # Go to the home directory on the server
            if [ ! -d "webhook-telegram" ]; then
              git clone https://github.com/YOUR_GITHUB_USERNAME/webhook-telegram.git
            else
              cd webhook-telegram
              git pull origin main  # Pull the latest code
            fi
            docker stop flask-app || true  # Stop any existing container
            docker rm flask-app || true    # Remove the old container
            docker rmi flask-app || true   # Remove the old image
            docker build -t flask-app .    # Build the new image from the latest code
            docker run -d -p 80:5000 --name flask-app flask-app:latest  # Run the new container
