name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_SERVER_IP }}
          username: ${{ secrets.HETZNER_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~
            if [ ! -d "webhook-telegram" ]; then
              git clone https://github.com/meernahro/webhook-telegram.git
            fi
            cd webhook-telegram
            git pull origin main
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker rmi fastapi-app || true
            if [ -f Dockerfile ]; then
              docker build -t fastapi-app .
            else
              echo "Dockerfile not found, exiting."
              exit 1
            fi
            docker run -d -p 8000:8000 --name fastapi-app \
              -e TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
              -e TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }} \
              -e BINANCE_API_KEY=${{ secrets.BINANCE_API_KEY }} \
              -e BINANCE_API_SECRET=${{ secrets.BINANCE_API_SECRET }} \
              fastapi-app:latest
